<a href="https://colab.research.google.com/github/AmarnathaGowda/PyTorch/blob/main/Intro_to_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to PyTorch**

**TENSORS**


*   A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.
*   Similar To Numpy Arrays, but full of fun things that make them  work better on GPU's.
*   PyTorch is an optimized tensor library for deep learning using GPUs and CPUs.
*   Default data type of float32. We can change as per the requirements.
* More suitable for deep learning than a numpy array.



In [ ]:
! pip list

In [2]:
import torch
import numpy as np

**LISTS**

In [5]:
#Single dimetion
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
#Multi Dimetions
my_list = [[1,2,3,4,5],[6,7,8,9]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9]]

**NUMPY** **ARRAYS**

In [7]:
np1 = np.random.rand(3,4)
np1

array([[0.68017848, 0.25696226, 0.57956809, 0.98308896],
       [0.66927475, 0.98666834, 0.39880589, 0.66957658],
       [0.05418929, 0.0952095 , 0.62740718, 0.46244409]])

**TENSORS**

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.1748, -0.3998,  1.0176, -1.1519],
        [-0.5921,  1.3498, -0.4989,  3.3772],
        [ 1.5024, -0.8232, -0.4029, -1.4942]])

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
# creating tensor using Numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.6802, 0.2570, 0.5796, 0.9831],
        [0.6693, 0.9867, 0.3988, 0.6696],
        [0.0542, 0.0952, 0.6274, 0.4624]], dtype=torch.float64)

# **Tensor Operations**

In [3]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
# Reshape if we dont know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch3 = my_torch2.view(2,-1)
my_torch3

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [10]:
# with reshape and view , they will update
my_torch4 = torch.arange(10)
my_torch4

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch5 = my_torch4.reshape(2,5)
my_torch5

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [13]:
my_torch4[0] = 100

In [17]:
my_torch4


tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [16]:
my_torch5

tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [18]:
# Slices
my_torch6 = torch.arange(10)
my_torch6

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
my_torch6[1]

tensor(1)

In [20]:
# grab Slice
my_torch7 = my_torch6.reshape(5,2)
my_torch7

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [21]:
my_torch7[:,1]

tensor([1, 3, 5, 7, 9])

In [22]:
#retun column
my_torch7[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])